# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = '''
 $directory $git_branch$git_status$python$rust$julia$golang$nim$elixir
 $character
'''
# right_format = """$python$rust$julia"""

# Replace the '❯' symbol in the prompt with void
[character] # The name of the module we are configuring is 'character'
success_symbol = '[](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[](bold red)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
style = "fg:#8EC07C"
format = "[$path](bold $style)"
truncation_length = 2
truncation_symbol = "…/"

[rust]
symbol = ' '

[julia]
symbol = ' '

[python]
symbol = ' '

[golang]
symbol = ''

[nim]
symbol = ''

[elixir]
symbol = ''
